import { useEffect, useState } from "react";
import { track } from "@/lib/track";
import { useNavigate } from "react-router-dom";
import { Logo } from "./Logo";
import type { FormAnswers } from "./FormView";
import { downloadBlueprintPdf, buildMarketingPrompt, flattenLaunchPlan } from "@/lib/exports";

interface LaunchPhase {
  title: string;
  timeframe: string;
  what_to_do: string;
  exact_steps: string[];
  real_life_example: string;
  tools: string[];
  success_looks_like: string;
}

type LaunchPlan = string | { phases: LaunchPhase[] };

interface RoadmapWeek {
  week: number;
  phase: string;
  title: string;
  hours: string;
  task: string;
  why: string;
  resource: {
    type: "BOOK" | "VIDEO" | "TOOL";
    title: string;
    description: string;
  };
}

interface RoadmapData {
  weeks: RoadmapWeek[];
}

interface ReportData {
  diagnosis: string;
  problem_and_demand: string;
  target_audience: string;
  clear_offer: string;
  tools_needed: string;
  ai_nocode_stack: string;
  launch_plan: LaunchPlan;
  pricing_strategy: string;
  distribution_channels: string;
  outreach_scripts: string;
  proof_needed: string;
  honest_risks: string;
  seven_day_plan: string;
  how_to_scale: string;
  roadmap?: RoadmapData;
}

interface ResultsViewProps {
  ideaName: string;
  answers: FormAnswers;
  report: ReportData;
  onStartOver: () => void;
  isPaid?: boolean;
  isShared?: boolean;
  roadmapLoading?: boolean;
  onFetchRoadmap?: () => void;
  generating?: boolean;
  chunksComplete?: number;
}

const FREE_SECTIONS = 3;
const FREE_ROADMAP_WEEKS = 2;

type SectionCategory = "strategy" | "market" | "build" | "growth";

const SECTIONS: { num: string; title: string; key: keyof ReportData; category: SectionCategory }[] = [
  { num: "01", title: "Business Idea Diagnosis",      key: "diagnosis",            category: "strategy" },
  { num: "02", title: "Real Problem & Demand",         key: "problem_and_demand",   category: "market"   },
  { num: "03", title: "Target Audience",               key: "target_audience",      category: "market"   },
  { num: "04", title: "Your Clear Offer",              key: "clear_offer",          category: "strategy" },
  { num: "05", title: "Tools You Need",                key: "tools_needed",         category: "build"    },
  { num: "06", title: "AI & No-Code Stack",            key: "ai_nocode_stack",      category: "build"    },
  { num: "07", title: "Step-by-Step Launch Plan",      key: "launch_plan",          category: "build"    },
  { num: "08", title: "Pricing Strategy",              key: "pricing_strategy",     category: "strategy" },
  { num: "09", title: "Distribution Channels",         key: "distribution_channels",category: "growth"   },
  { num: "10", title: "Outreach Scripts",              key: "outreach_scripts",     category: "growth"   },
  { num: "11", title: "Proof & Demo to Create",        key: "proof_needed",         category: "growth"   },
  { num: "12", title: "Honest Risks",                  key: "honest_risks",         category: "strategy" },
  { num: "13", title: "Your First 7-Day Action Plan",  key: "seven_day_plan",       category: "build"    },
  { num: "14", title: "How to Scale Later",            key: "how_to_scale",         category: "growth"   },
];

const CATEGORY_STYLES: Record<SectionCategory, { border: string; badge: string; text: string }> = {
  strategy: { border: "border-t-[#4f46e5]", badge: "bg-indigo-50 text-indigo-600",   text: "text-indigo-600" },
  market:   { border: "border-t-[#16a34a]", badge: "bg-green-50 text-green-700",     text: "text-green-700"  },
  build:    { border: "border-t-[#ea580c]", badge: "bg-orange-50 text-orange-600",   text: "text-orange-600" },
  growth:   { border: "border-t-[#9333ea]", badge: "bg-purple-50 text-purple-600",   text: "text-purple-600" },
};

const PLANS = [
  { id: "one_off",  name: "One blueprint", desc: "This blueprint only · No subscription", price: "£9",  period: "one-off",   popular: false },
  { id: "monthly",  name: "10 tokens",     desc: "10 blueprints · £1.90/token",           price: "£19", period: "one-off",   popular: true  },
  { id: "sub",      name: "Monthly",       desc: "20 tokens/mo · Rollover unused",        price: "£19", period: "per month", popular: false },
];

const PHASE_COLOURS: Record<string, { bg: string; text: string; border: string }> = {
  FOUNDATION: { bg: "bg-indigo-50",  text: "text-indigo-600",  border: "border-indigo-100" },
  VALIDATION: { bg: "bg-orange-50",  text: "text-orange-600",  border: "border-orange-100" },
  LAUNCH:     { bg: "bg-green-50",   text: "text-green-700",   border: "border-green-100"  },
};

const RESOURCE_ICON: Record<string, string> = { BOOK: "📖", VIDEO: "▶️", TOOL: "🛠️" };

const buildPlainText = (idea: string, report: ReportData): string =>
  `MY SOLOBLUEPRINT\n${idea}\nGenerated by SoloBlueprint · soloblueprint.co.uk\n\n` +
  SECTIONS.map(s => `${s.num} · ${s.title.toUpperCase()}\n${typeof report[s.key] === "string" ? report[s.key] : flattenLaunchPlan(report[s.key] as LaunchPlan)}`).join("\n\n");

const copyToClipboard = async (text: string) => {
  try { await navigator.clipboard.writeText(text); }
  catch { const ta = document.createElement("textarea"); ta.value = text; document.body.appendChild(ta); ta.select(); document.execCommand("copy"); document.body.removeChild(ta); }
};

const PhaseCard = ({ phase, index }: { phase: LaunchPhase; index: number }) => {
  const [open, setOpen] = useState(index === 0);
  return (
    <div className="overflow-hidden rounded-lg border border-border bg-background/40 mb-2">
      <button type="button" onClick={() => setOpen(o => !o)}
        className="flex w-full items-start justify-between gap-3 px-4 py-3 text-left hover:bg-muted/30 transition">
        <div className="flex flex-1 items-baseline gap-3">
          <span className="text-[11px] font-bold text-orange-500">P{index + 1}</span>
          <div>
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground">{phase.timeframe}</p>
            <p className="text-sm font-semibold text-foreground mt-0.5">{phase.title}</p>
          </div>
        </div>
        <span className="text-xs text-muted-foreground mt-1">{open ? "−" : "+"}</span>
      </button>
      {open && (
        <div className="border-t border-border px-4 py-4 space-y-4 text-sm text-muted-foreground leading-relaxed">
          <p className="whitespace-pre-line">{phase.what_to_do}</p>
          <ol className="space-y-2">
            {phase.exact_steps.map((step, i) => (
              <li key={i} className="flex gap-3">
                <span className="text-xs font-bold text-orange-500 shrink-0">{i + 1}.</span>
                <p className="whitespace-pre-line flex-1">{step}</p>
              </li>
            ))}
          </ol>
          <div className="rounded-lg border border-orange-100 bg-orange-50/50 p-3">
            <p className="text-[10px] font-bold uppercase tracking-wider text-orange-600 mb-1">Real example</p>
            <p className="whitespace-pre-line text-foreground/80">{phase.real_life_example}</p>
          </div>
          <div>
            <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-2">Tools</p>
            <ul className="space-y-1">{phase.tools.map((t, i) => <li key={i} className="flex gap-2"><span className="text-orange-400">•</span>{t}</li>)}</ul>
          </div>
          <p className="border-t border-border pt-3 text-foreground/70 italic">{phase.success_looks_like}</p>
        </div>
      )}
    </div>
  );
};

const SectionCard = ({ section, content, locked = false }: {
  section: typeof SECTIONS[0]; content: string | LaunchPlan; locked?: boolean;
}) => {
  const styles = CATEGORY_STYLES[section.category];
  const isLaunch = section.key === "launch_plan";
  const phases = isLaunch && typeof content === "object" && "phases" in (content as object)
    ? (content as { phases: LaunchPhase[] }).phases : null;

  return (
    <div className={`bg-card rounded-2xl border border-border border-t-2 ${styles.border} mb-3 overflow-hidden transition hover:shadow-sm ${locked ? "opacity-40 blur-[1.5px] pointer-events-none select-none" : ""}`}>
      <div className="flex items-center gap-3 px-5 pt-5 pb-2">
        <div className={`flex items-center justify-center w-7 h-7 rounded-lg text-[11px] font-bold flex-shrink-0 ${styles.badge}`}>
          {section.num}
        </div>
        <h2 className="font-display text-base sm:text-lg text-foreground">{section.title}</h2>
      </div>
      <div className="px-5 pb-5 pl-[60px]">
        {phases ? (
          <div className="mt-2">{phases.map((p, i) => <PhaseCard key={i} phase={p} index={i} />)}</div>
        ) : (
          <p className="text-sm sm:text-[15px] text-muted-foreground leading-[1.85] whitespace-pre-line">
            {typeof content === "string" ? content : flattenLaunchPlan(content)}
          </p>
        )}
      </div>
    </div>
  );
};

const WeekCard = ({ week, locked = false }: { week: RoadmapWeek; locked?: boolean }) => {
  const [completed, setCompleted] = useState(false);
  const phaseStyle = PHASE_COLOURS[week.phase] ?? PHASE_COLOURS.FOUNDATION;

  if (locked) {
    return (
      <div className="rounded-2xl border border-border bg-card mb-3 p-5 opacity-40 blur-[1.5px] pointer-events-none select-none">
        <div className="flex items-center gap-3 mb-3">
          <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded-full border ${phaseStyle.bg} ${phaseStyle.text} ${phaseStyle.border}`}>
            {week.phase}
          </span>
          <span className="text-[10px] text-muted-foreground font-medium">{week.hours}</span>
        </div>
        <p className="font-display text-base text-foreground mb-1">Week {week.week} : {week.title}</p>
        <div className="h-2 w-3/4 rounded bg-muted/50 mb-2 mt-3" />
        <div className="h-2 w-1/2 rounded bg-muted/50" />
      </div>
    );
  }

  return (
    <div className={`rounded-2xl border bg-card mb-3 overflow-hidden transition ${completed ? "border-green-200 bg-green-50/30" : "border-border"}`}>
      <div className="px-5 pt-5 pb-4">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded-full border ${phaseStyle.bg} ${phaseStyle.text} ${phaseStyle.border}`}>
              {week.phase}
            </span>
            <span className="text-[10px] text-muted-foreground font-medium">{week.hours}</span>
          </div>
          {completed && <span className="text-[10px] font-semibold text-green-600">✓ Complete</span>}
        </div>
        <p className="font-display text-base text-foreground mb-3">Week {week.week} : {week.title}</p>
        <p className="text-sm text-muted-foreground leading-relaxed mb-2">{week.task}</p>
        <p className="text-xs text-muted-foreground/70 italic leading-relaxed mb-4">{week.why}</p>

        {week.resource && (
          <div className={`rounded-xl border p-3 mb-4 ${phaseStyle.border} ${phaseStyle.bg}/40`}>
            <p className={`text-[10px] font-bold uppercase tracking-wider mb-1 ${phaseStyle.text}`}>
              {RESOURCE_ICON[week.resource.type]} {week.resource.type}
            </p>
            <p className="text-sm font-semibold text-foreground">{week.resource.title}</p>
            <p className="text-xs text-muted-foreground mt-0.5">{week.resource.description}</p>
          </div>
        )}

        <button
          type="button"
          onClick={() => setCompleted(c => !c)}
          className={`w-full rounded-xl py-2.5 text-sm font-semibold transition ${
            completed
              ? "bg-green-100 text-green-700 border border-green-200"
              : "bg-primary text-white shadow-[0_2px_12px_rgba(79,70,229,0.25)] hover:brightness-110"
          }`}
        >
          {completed ? "✓ Marked complete" : "Mark complete & check in →"}
        </button>
      </div>
    </div>
  );
};

const RoadmapPaywall = ({ onUnlock }: { onUnlock: () => void }) => (
  <div className="relative mt-2">
    <div className="pointer-events-none select-none space-y-3 opacity-30 blur-sm mb-[-60px]">
      {[3, 4].map(w => (
        <div key={w} className="rounded-2xl border border-border bg-card p-5">
          <div className="h-2 w-1/3 rounded bg-muted/50 mb-3" />
          <div className="h-2 w-2/3 rounded bg-muted/50 mb-2" />
          <div className="h-2 w-1/2 rounded bg-muted/50" />
        </div>
      ))}
    </div>
    <div className="relative rounded-2xl border border-indigo-100 bg-background shadow-[0_-8px_40px_rgba(79,70,229,0.1)] p-6 text-center">
      <div className="text-2xl mb-2">🔒</div>
      <h2 className="font-display text-xl text-foreground mb-1">Your path continues beyond here</h2>
      <p className="text-sm text-muted-foreground mb-5">Weeks 3–6 cover Validation and Launch. Unlock your full roadmap, progress tracking, and weekly steps.</p>
      <button type="button" onClick={onUnlock}
        className="w-full rounded-xl bg-primary py-3 text-sm font-semibold text-white shadow-[0_4px_20px_rgba(79,70,229,0.35)] hover:brightness-110 transition">
        Unlock my full path →
      </button>
      <p className="mt-3 text-[11px] text-muted-foreground">Secure payment via Stripe · Tokens never expire</p>
    </div>
  </div>
);

const PaywallGate = () => {
  const [selected, setSelected] = useState("monthly");
  useEffect(() => { track("paywall_view"); }, []);
  const navigate = useNavigate();
  return (
    <div className="relative mt-2">
      <div className="pointer-events-none select-none space-y-3 opacity-30 blur-sm mb-[-60px]">
        {SECTIONS.slice(FREE_SECTIONS, FREE_SECTIONS + 2).map(s => (
          <div key={s.num} className="bg-card rounded-2xl border border-border p-5">
            <div className="flex items-center gap-3 mb-3">
              <div className={`w-7 h-7 rounded-lg ${CATEGORY_STYLES[s.category].badge} flex items-center justify-center text-[11px] font-bold`}>{s.num}</div>
              <span className="font-display text-base">{s.title}</span>
            </div>
            <div className="h-2 w-3/4 rounded bg-muted/50 mb-2" />
            <div className="h-2 w-1/2 rounded bg-muted/50" />
          </div>
        ))}
      </div>
      <div className="relative rounded-2xl border border-indigo-100 bg-background shadow-[0_-8px_40px_rgba(79,70,229,0.1)] backdrop-blur p-6">
        <div className="text-center mb-5">
          <div className="text-2xl mb-2">🔓</div>
          <h2 className="font-display text-xl text-foreground mb-1">Unlock your full blueprint</h2>
          <p className="text-sm text-muted-foreground">11 more sections : tools, pricing, outreach scripts, 7-day action plan.</p>
        </div>
        <div className="space-y-2.5 mb-5">
          {PLANS.map(plan => (
            <button key={plan.id} type="button" onClick={() => setSelected(plan.id)}
              className={`w-full flex items-center justify-between rounded-xl border px-4 py-3 text-left transition ${selected === plan.id ? "border-primary bg-primary/5" : "border-border hover:border-primary/40"}`}>
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold text-foreground">{plan.name}</span>
                  {plan.popular && <span className="rounded-full bg-primary px-2 py-0.5 text-[10px] font-semibold text-white">Popular</span>}
                </div>
                <p className="text-xs text-muted-foreground mt-0.5">{plan.desc}</p>
              </div>
              <div className="text-right">
                <span className="font-display text-lg text-foreground">{plan.price}</span>
                <p className="text-[10px] text-muted-foreground">{plan.period}</p>
              </div>
            </button>
          ))}
        </div>
        <button type="button" onClick={() => navigate("/app/auth")}
          className="w-full rounded-xl bg-primary py-3 text-sm font-semibold text-white shadow-[0_4px_20px_rgba(79,70,229,0.35)] transition hover:brightness-110">
          Continue to payment →
        </button>
        <p className="mt-3 text-center text-[11px] text-muted-foreground">Secure payment via Stripe · Tokens never expire</p>
      </div>
    </div>
  );
};


const SkeletonCard = ({ num, title }: { num: string; title: string }) => (
  <div className="bg-card rounded-2xl border border-border border-t-2 border-t-muted mb-3 overflow-hidden animate-pulse">
    <div className="flex items-center gap-3 px-5 pt-5 pb-2">
      <div className="w-7 h-7 rounded-lg bg-muted flex-shrink-0" />
      <div className="h-4 w-48 rounded bg-muted" />
    </div>
    <div className="px-5 pb-5 pl-[60px] space-y-2">
      <div className="h-3 w-full rounded bg-muted/60" />
      <div className="h-3 w-5/6 rounded bg-muted/60" />
      <div className="h-3 w-4/6 rounded bg-muted/60" />
    </div>
  </div>
);

const RoadmapSkeletonLoader = ({ count = 6 }: { count?: number }) => (
  <div className="space-y-3">
    {Array.from({ length: count }).map((_, i) => (
      <div
        key={i}
        className="rounded-2xl border border-border bg-card p-5 animate-pulse"
        style={{
          animation: `slideIn 0.4s ease-out ${i * 0.08}s both`,
        }}
      >
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <div className="w-12 h-6 rounded-full bg-muted" />
            <div className="w-16 h-4 rounded bg-muted" />
          </div>
        </div>
        <div className="h-5 w-1/3 rounded bg-muted mb-3" />
        <div className="space-y-2 mb-4">
          <div className="h-3 w-full rounded bg-muted/60" />
          <div className="h-3 w-5/6 rounded bg-muted/60" />
        </div>
        <div className="h-20 w-full rounded-lg bg-muted/40" />
      </div>
    ))}
  </div>
);

export const ResultsView = ({ ideaName, answers, report, onStartOver, isPaid = false, isShared = false, roadmapLoading = false, onFetchRoadmap, generating = false, chunksComplete = 0 }: ResultsViewProps) => {
  const navigate = useNavigate();
  const [copied, setCopied] = useState(false);
  const [shareCopied, setShareCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<"blueprint" | "roadmap">("blueprint");

  const handleCopy = async () => { await copyToClipboard(buildPlainText(ideaName, report)); setCopied(true); setTimeout(() => setCopied(false), 2000); };
  const handleShare = async () => { await copyToClipboard(window.location.href); setShareCopied(true); setTimeout(() => setShareCopied(false), 2000); };
  const handleDownloadPdf = () => downloadBlueprintPdf(ideaName, answers, report);

  const meta = [answers.budget, answers.hours, answers.experience, answers.goal].filter(Boolean);
  const freeSections = SECTIONS.slice(0, FREE_SECTIONS);
  const lockedSections = SECTIONS.slice(FREE_SECTIONS);

  const roadmapWeeks = report.roadmap?.weeks ?? [];
  const freeWeeks = roadmapWeeks.slice(0, FREE_ROADMAP_WEEKS);
  const lockedWeeks = roadmapWeeks.slice(FREE_ROADMAP_WEEKS);

  return (
    <div className="min-h-screen bg-background">
      {/* Sticky action bar */}
      <div className="sticky top-0 z-20 border-b border-border bg-background/90 backdrop-blur">
        <div className="mx-auto flex max-w-[720px] items-center justify-between gap-2 px-3 py-2.5 sm:px-6">
          <Logo size="sm" />
          <div className="flex items-center gap-2">
            {isPaid && !isShared && (
              <>
                <button onClick={handleDownloadPdf}
                  className="inline-flex items-center gap-1.5 rounded-full bg-primary px-3 py-1.5 text-xs font-semibold text-white shadow-[0_2px_10px_rgba(79,70,229,0.3)] transition hover:brightness-110">
                  ↓ PDF
                </button>
                <button onClick={handleShare}
                  className="inline-flex items-center gap-1.5 rounded-full border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground transition hover:border-primary/40 hover:text-primary">
                  {shareCopied ? "✓ Copied" : "Share"}
                </button>
                <button onClick={handleCopy} className="hidden sm:block text-xs text-muted-foreground hover:text-foreground transition px-2">
                  {copied ? "✓" : "Copy"}
                </button>
              </>
            )}
            {isShared && (
              <button onClick={() => navigate("/")}
                className="rounded-full bg-primary px-3 py-1.5 text-xs font-semibold text-white transition hover:brightness-110">
                Build mine →
              </button>
            )}
            {!isShared && (
              <button onClick={onStartOver} className="text-xs text-muted-foreground hover:text-foreground transition px-2">
                Start Over
              </button>
            )}
          </div>
        </div>

        {/* Tabs */}
        <div className="mx-auto max-w-[720px] px-3 sm:px-6 flex gap-0 border-t border-border">
          <button
            type="button"
            onClick={() => setActiveTab("blueprint")}
            className={`flex items-center gap-1.5 px-4 py-2.5 text-xs font-semibold border-b-2 transition ${activeTab === "blueprint" ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}
          >
            📋 Blueprint
          </button>
          <button
            type="button"
            onClick={() => {
              setActiveTab("roadmap");
              if (!report.roadmap?.weeks?.length && !roadmapLoading && onFetchRoadmap) {
                onFetchRoadmap();
              }
            }}
            className={`flex items-center gap-1.5 px-4 py-2.5 text-xs font-semibold border-b-2 transition ${activeTab === "roadmap" ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}
          >
{roadmapLoading ? "🗺️ Roadmap ..." : "🗺️ Roadmap"}
          </button>
        </div>
      </div>

      <main className="mx-auto max-w-[720px] px-3 py-6 sm:px-6 sm:py-10">
        {/* Hero header */}
        <div className="mb-6">
          <p className="text-[11px] font-semibold uppercase tracking-widest text-primary mb-2">Your SoloBlueprint for:</p>
          <h1 className="font-display text-2xl sm:text-4xl text-foreground mb-3">{ideaName}</h1>
          {meta.length > 0 && (
            <div className="flex flex-wrap gap-1.5">
              {meta.map(m => (
                <span key={m} className="rounded-full bg-indigo-50 border border-indigo-100 px-3 py-1 text-xs text-indigo-600 font-medium">{m}</span>
              ))}
            </div>
          )}
        </div>

        {/* Blueprint tab */}
        {activeTab === "blueprint" && (
          <>
            {!generating && (
              <div className="flex flex-wrap gap-3 mb-5">
                {(Object.entries(CATEGORY_STYLES) as [SectionCategory, typeof CATEGORY_STYLES[SectionCategory]][]).map(([cat, styles]) => (
                  <div key={cat} className="flex items-center gap-1.5">
                    <div className={`w-2 h-2 rounded-sm ${styles.badge}`} />
                    <span className={`text-[11px] font-medium capitalize ${styles.text}`}>{cat}</span>
                  </div>
                ))}
              </div>
            )}

            {generating && chunksComplete === 0 && (
              <div className="flex items-center gap-2 mb-5 text-sm text-muted-foreground">
                <span className="h-2 w-2 rounded-full bg-primary animate-pulse" />
                Analysing your idea...
              </div>
            )}

            {SECTIONS.map((section, idx) => {
              const hasContent = !!report[section.key];
              const isLocked = !isPaid && idx >= FREE_SECTIONS;

              if (hasContent) {
                return (
                  <div key={section.num} className="animate-fade-in">
                    <SectionCard section={section} content={report[section.key] as string | LaunchPlan} locked={isLocked} />
                  </div>
                );
              }

              if (generating) {
                return <SkeletonCard key={section.num} num={section.num} title={section.title} />;
              }

              if (isLocked) {
                return idx === FREE_SECTIONS ? <PaywallGate key="paywall" /> : null;
              }

              return null;
            })}
          </>
        )}

        {/* Roadmap tab */}
        {activeTab === "roadmap" && (
          <>
            <div className="mb-5">
              <p className="text-sm text-muted-foreground leading-relaxed">
                Week by week. No noise. One resource per step : curated for your idea.
              </p>
            </div>

            {roadmapLoading ? (
              <>
                <div className="rounded-2xl border border-border bg-card p-4 mb-4 flex items-center gap-2 text-sm text-muted-foreground">
                  <span className="h-2 w-2 rounded-full bg-primary animate-pulse" />
                  Building your roadmap...
                </div>
                <RoadmapSkeletonLoader count={6} />
              </>
            ) : roadmapWeeks.length === 0 ? (
              <div className="rounded-2xl border border-border bg-card p-8 text-center">
                <p className="text-lg mb-2">🗺️</p>
                <p className="text-sm font-semibold text-foreground mb-1">Your roadmap is ready to build</p>
                <p className="text-xs text-muted-foreground mb-4">6 weeks. One task per week. Curated resources for your idea.</p>
                {onFetchRoadmap && (
                  <button
                    type="button"
                    onClick={onFetchRoadmap}
                    className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-white shadow-[0_2px_12px_rgba(79,70,229,0.25)] hover:brightness-110 transition"
                  >
                    Generate my roadmap →
                  </button>
                )}
              </div>
            ) : (
              <>
                {freeWeeks.map((week, idx) => (
                  <div
                    key={week.week}
                    style={{
                      animation: `slideIn 0.4s ease-out ${idx * 0.08}s both`,
                    }}
                  >
                    <WeekCard week={week} />
                  </div>
                ))}

                {isPaid ? (
                  lockedWeeks.map((week, idx) => (
                    <div
                      key={week.week}
                      style={{
                        animation: `slideIn 0.4s ease-out ${(freeWeeks.length + idx) * 0.08}s both`,
                      }}
                    >
                      <WeekCard week={week} />
                    </div>
                  ))
                ) : (
                  lockedWeeks.length > 0 && <RoadmapPaywall onUnlock={() => navigate("/app/auth")} />
                )}
              </>
            )}
          </>
        )}

        <footer className="mt-12 border-t border-border pt-5 text-center text-xs text-muted-foreground">
          <p className="mb-2 text-[11px] leading-relaxed">
            This blueprint is AI-generated information, not professional, legal, financial, or tax advice. Verify facts and figures before acting. See our <a href="/terms" className="underline hover:text-foreground">Terms</a>.
          </p>
          SoloBlueprint · soloblueprint.co.uk
        </footer>
      </main>
    </div>
  );
};
