import { useState } from "react";
import { Logo } from "./Logo";
import type { FormAnswers } from "./FormView";
import { downloadBlueprintPdf, buildMarketingPrompt, flattenLaunchPlan } from "@/lib/exports";

interface LaunchPhase {
  title: string;
  timeframe: string;
  what_to_do: string;
  exact_steps: string[];
  real_life_example: string;
  tools: string[];
  success_looks_like: string;
}

type LaunchPlan = string | { phases: LaunchPhase[] };

interface ReportData {
  diagnosis: string;
  problem_and_demand: string;
  target_audience: string;
  clear_offer: string;
  tools_needed: string;
  ai_nocode_stack: string;
  launch_plan: LaunchPlan;
  pricing_strategy: string;
  distribution_channels: string;
  outreach_scripts: string;
  proof_needed: string;
  honest_risks: string;
  seven_day_plan: string;
  how_to_scale: string;
}

interface ResultsViewProps {
  ideaName: string;
  answers: FormAnswers;
  report: ReportData;
  onStartOver: () => void;
}

const SECTIONS: { num: string; title: string; key: keyof ReportData }[] = [
  { num: "01", title: "Business Idea Diagnosis", key: "diagnosis" },
  { num: "02", title: "Real Problem & Demand", key: "problem_and_demand" },
  { num: "03", title: "Target Audience", key: "target_audience" },
  { num: "04", title: "Your Clear Offer", key: "clear_offer" },
  { num: "05", title: "Tools You Need", key: "tools_needed" },
  { num: "06", title: "AI & No-Code Stack", key: "ai_nocode_stack" },
  { num: "07", title: "Step-by-Step Launch Plan", key: "launch_plan" },
  { num: "08", title: "Pricing Strategy", key: "pricing_strategy" },
  { num: "09", title: "Distribution Channels", key: "distribution_channels" },
  { num: "10", title: "Outreach Scripts", key: "outreach_scripts" },
  { num: "11", title: "Proof & Demo to Create", key: "proof_needed" },
  { num: "12", title: "Honest Risks", key: "honest_risks" },
  { num: "13", title: "Your First 7-Day Action Plan", key: "seven_day_plan" },
  { num: "14", title: "How to Scale Later", key: "how_to_scale" },
];

const buildPlainText = (idea: string, report: ReportData): string => {
  return `MY SOLOBLUEPRINT
${idea}
Generated by SoloBlueprint · soloblueprint.co.uk
==========================================

01 · BUSINESS IDEA DIAGNOSIS
${report.diagnosis}

02 · REAL PROBLEM & DEMAND
${report.problem_and_demand}

03 · TARGET AUDIENCE
${report.target_audience}

04 · YOUR CLEAR OFFER
${report.clear_offer}

05 · TOOLS YOU NEED
${report.tools_needed}

06 · AI & NO-CODE STACK
${report.ai_nocode_stack}

07 · STEP-BY-STEP LAUNCH PLAN
${flattenLaunchPlan(report.launch_plan)}

08 · PRICING STRATEGY
${report.pricing_strategy}

09 · DISTRIBUTION CHANNELS
${report.distribution_channels}

10 · OUTREACH SCRIPTS
${report.outreach_scripts}

11 · PROOF & DEMO TO CREATE
${report.proof_needed}

12 · HONEST RISKS
${report.honest_risks}

13 · YOUR FIRST 7-DAY ACTION PLAN
${report.seven_day_plan}

14 · HOW TO SCALE LATER
${report.how_to_scale}

==========================================
Build your solo business at soloblueprint.co.uk`;
};

const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    const ta = document.createElement("textarea");
    ta.value = text;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand("copy");
    document.body.removeChild(ta);
  }
};

const CopyButton = ({ text, label = "Copy" }: { text: string; label?: string }) => {
  const [done, setDone] = useState(false);
  return (
    <button
      type="button"
      onClick={async (e) => {
        e.stopPropagation();
        await copyToClipboard(text);
        setDone(true);
        setTimeout(() => setDone(false), 1500);
      }}
      className="inline-flex items-center gap-1 rounded-md border border-border bg-background/40 px-2 py-1 text-[10px] font-medium uppercase tracking-wider text-muted-foreground transition hover:border-primary/50 hover:text-foreground"
    >
      {done ? "Copied ✓" : label}
    </button>
  );
};

const PhaseCard = ({ phase, index, defaultOpen }: { phase: LaunchPhase; index: number; defaultOpen: boolean }) => {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="overflow-hidden rounded-lg border border-border bg-background/40">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-start justify-between gap-3 px-4 py-3 text-left transition hover:bg-background/60"
      >
        <div className="flex flex-1 items-baseline gap-3">
          <span className="font-mono-num text-[11px] text-primary">P{index + 1}</span>
          <div className="flex-1">
            <p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">
              {phase.timeframe}
            </p>
            <p className="mt-0.5 text-sm font-semibold text-foreground sm:text-[15px]">
              {phase.title}
            </p>
          </div>
        </div>
        <span className="mt-1 text-xs text-muted-foreground" aria-hidden>
          {open ? "−" : "+"}
        </span>
      </button>

      {open && (
        <div className="space-y-5 border-t border-border px-4 py-4 text-sm leading-relaxed text-muted-foreground sm:text-[14px] sm:leading-[1.7]">
          <div>
            <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-foreground/80">
              What to do
            </p>
            <p className="whitespace-pre-line">{phase.what_to_do}</p>
          </div>

          <div>
            <p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-foreground/80">
              Exact steps
            </p>
            <ol className="space-y-2">
              {phase.exact_steps.map((step, i) => (
                <li key={i} className="flex gap-3">
                  <span className="font-mono-num shrink-0 text-xs text-primary">{i + 1}.</span>
                  <div className="flex-1">
                    <p className="whitespace-pre-line">{step}</p>
                    <div className="mt-1">
                      <CopyButton text={step} label="Copy step" />
                    </div>
                  </div>
                </li>
              ))}
            </ol>
          </div>

          <div className="rounded-md border border-primary/30 bg-primary/5 p-3">
            <div className="mb-1 flex items-center justify-between gap-2">
              <p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-primary">
                Real-life example
              </p>
              <CopyButton text={phase.real_life_example} label="Copy example" />
            </div>
            <p className="whitespace-pre-line text-foreground/90">{phase.real_life_example}</p>
          </div>

          <div>
            <p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-foreground/80">
              Tools
            </p>
            <ul className="space-y-1.5">
              {phase.tools.map((tool, i) => (
                <li key={i} className="flex gap-2">
                  <span className="text-primary">•</span>
                  <span className="flex-1 whitespace-pre-line">{tool}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="border-t border-border pt-3">
            <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-foreground/80">
              What success looks like
            </p>
            <p className="whitespace-pre-line">{phase.success_looks_like}</p>
          </div>
        </div>
      )}
    </div>
  );
};

const LaunchPlanSection = ({ num, title, plan }: { num: string; title: string; plan: LaunchPlan }) => {
  const isDesktop = typeof window !== "undefined" && window.matchMedia("(min-width: 768px)").matches;

  if (typeof plan === "string" || !plan?.phases?.length) {
    const text = typeof plan === "string" ? plan : "";
    return (
      <article className="animate-fade-in rounded-xl border border-border border-l-2 border-l-primary bg-card p-5 sm:p-6">
        <div className="mb-3 flex items-baseline gap-3">
          <span className="font-mono-num text-xs text-muted-foreground">{num}</span>
          <h2 className="text-base font-semibold text-foreground sm:text-lg">{title}</h2>
        </div>
        <p className="whitespace-pre-line text-sm leading-relaxed text-muted-foreground sm:text-[15px] sm:leading-[1.7]">
          {text}
        </p>
      </article>
    );
  }

  return (
    <article className="animate-fade-in rounded-xl border border-border border-l-2 border-l-primary bg-card p-5 sm:p-6">
      <div className="mb-4 flex items-baseline gap-3">
        <span className="font-mono-num text-xs text-muted-foreground">{num}</span>
        <h2 className="text-base font-semibold text-foreground sm:text-lg">{title}</h2>
      </div>
      <p className="mb-4 text-xs text-muted-foreground sm:text-sm">
        Five sequential phases covering the first 14 days. Tap a phase to expand.
      </p>
      <div className="space-y-3">
        {plan.phases.map((phase, i) => (
          <PhaseCard key={i} phase={phase} index={i} defaultOpen={isDesktop} />
        ))}
      </div>
    </article>
  );
};

export const ResultsView = ({ ideaName, answers, report, onStartOver }: ResultsViewProps) => {
  const [copied, setCopied] = useState(false);
  const [promptCopied, setPromptCopied] = useState(false);

  const copyText = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
    }
  };

  const handleCopy = async () => {
    await copyText(buildPlainText(ideaName, report));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyPrompt = async () => {
    await copyText(buildMarketingPrompt(ideaName, answers, report));
    setPromptCopied(true);
    setTimeout(() => setPromptCopied(false), 2000);
  };

  const handleDownloadPdf = () => {
    downloadBlueprintPdf(ideaName, answers, report);
  };

  const meta = [answers.budget, answers.hours, answers.experience, answers.goal]
    .filter(Boolean)
    .join(" · ");

  return (
    <div className="min-h-screen">
      {/* Sticky action bar */}
      <div className="sticky top-0 z-20 border-b border-border bg-background/85 backdrop-blur supports-[backdrop-filter]:bg-background/70">
        <div className="mx-auto flex max-w-[820px] items-center justify-between gap-3 px-4 py-3 sm:px-6">
          <Logo size="sm" />
          <div className="flex flex-wrap items-center justify-end gap-2">
            <button
              onClick={handleDownloadPdf}
              className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground shadow-[0_8px_24px_-12px_hsl(var(--primary)/0.7)] transition hover:brightness-110 sm:text-sm"
            >
              ↓ PDF
            </button>
            <button
              onClick={handleCopyPrompt}
              className="rounded-lg border border-primary/60 bg-transparent px-3 py-2 text-xs font-semibold text-primary transition hover:bg-primary/10 sm:text-sm"
            >
              {promptCopied ? "Copied ✓" : "Marketing Prompt"}
            </button>
            <button
              onClick={handleCopy}
              className="rounded-lg border border-border bg-transparent px-3 py-2 text-xs font-medium text-muted-foreground transition hover:border-primary/50 hover:text-foreground sm:text-sm"
            >
              {copied ? "Copied ✓" : "Copy Plan"}
            </button>
            <button
              onClick={onStartOver}
              className="rounded-lg px-3 py-2 text-xs font-medium text-muted-foreground transition hover:text-foreground sm:text-sm"
            >
              Start Over
            </button>
          </div>
        </div>
      </div>

      <main className="mx-auto w-full max-w-[820px] px-4 py-10 sm:px-6 sm:py-14">
        <p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">
          Your SoloBlueprint for:
        </p>
        <h1 className="mt-2 font-display text-3xl text-foreground sm:text-4xl md:text-5xl">
          {ideaName}
        </h1>
        {meta && (
          <p className="mt-3 text-xs text-muted-foreground sm:text-sm">{meta}</p>
        )}

        <div className="mt-10 space-y-5">
          {SECTIONS.map((section) => {
            if (section.key === "launch_plan") {
              return (
                <LaunchPlanSection
                  key={section.num}
                  num={section.num}
                  title={section.title}
                  plan={report.launch_plan}
                />
              );
            }
            return (
              <article
                key={section.num}
                className="animate-fade-in rounded-xl border border-border border-l-2 border-l-primary bg-card p-5 sm:p-6"
              >
                <div className="mb-3 flex items-baseline gap-3">
                  <span className="font-mono-num text-xs text-muted-foreground">
                    {section.num}
                  </span>
                  <h2 className="text-base font-semibold text-foreground sm:text-lg">
                    {section.title}
                  </h2>
                </div>
                <p className="whitespace-pre-line text-sm leading-relaxed text-muted-foreground sm:text-[15px] sm:leading-[1.7]">
                  {report[section.key] as string}
                </p>
              </article>
            );
          })}
        </div>

        <footer className="mt-14 border-t border-border pt-6 text-center text-xs text-muted-foreground">
          SoloBlueprint · Built for solo founders · soloblueprint.co.uk
        </footer>
      </main>
    </div>
  );
};
