import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Logo } from "./Logo";
import type { FormAnswers } from "./FormView";
import { downloadBlueprintPdf, buildMarketingPrompt, flattenLaunchPlan } from "@/lib/exports";

interface LaunchPhase {
  title: string;
  timeframe: string;
  what_to_do: string;
  exact_steps: string[];
  real_life_example: string;
  tools: string[];
  success_looks_like: string;
}

type LaunchPlan = string | { phases: LaunchPhase[] };

interface ReportData {
  diagnosis: string;
  problem_and_demand: string;
  target_audience: string;
  clear_offer: string;
  tools_needed: string;
  ai_nocode_stack: string;
  launch_plan: LaunchPlan;
  pricing_strategy: string;
  distribution_channels: string;
  outreach_scripts: string;
  proof_needed: string;
  honest_risks: string;
  seven_day_plan: string;
  how_to_scale: string;
}

interface ResultsViewProps {
  ideaName: string;
  answers: FormAnswers;
  report: ReportData;
  onStartOver: () => void;
  isPaid?: boolean;
}

const FREE_SECTIONS = 3;

const SECTIONS: { num: string; title: string; key: keyof ReportData }[] = [
  { num: "01", title: "Business Idea Diagnosis", key: "diagnosis" },
  { num: "02", title: "Real Problem & Demand", key: "problem_and_demand" },
  { num: "03", title: "Target Audience", key: "target_audience" },
  { num: "04", title: "Your Clear Offer", key: "clear_offer" },
  { num: "05", title: "Tools You Need", key: "tools_needed" },
  { num: "06", title: "AI & No-Code Stack", key: "ai_nocode_stack" },
  { num: "07", title: "Step-by-Step Launch Plan", key: "launch_plan" },
  { num: "08", title: "Pricing Strategy", key: "pricing_strategy" },
  { num: "09", title: "Distribution Channels", key: "distribution_channels" },
  { num: "10", title: "Outreach Scripts", key: "outreach_scripts" },
  { num: "11", title: "Proof & Demo to Create", key: "proof_needed" },
  { num: "12", title: "Honest Risks", key: "honest_risks" },
  { num: "13", title: "Your First 7-Day Action Plan", key: "seven_day_plan" },
  { num: "14", title: "How to Scale Later", key: "how_to_scale" },
];

const PLANS = [
  {
    id: "one_off",
    name: "One blueprint",
    desc: "This blueprint only. No subscription.",
    price: "£9",
    period: "one-off",
    popular: false,
  },
  {
    id: "monthly",
    name: "Monthly",
    desc: "Unlimited blueprints per month.",
    price: "£19",
    period: "per month",
    popular: true,
  },
  {
    id: "yearly",
    name: "Yearly",
    desc: "Unlimited · Save £149 vs monthly.",
    price: "£79",
    period: "per year",
    popular: false,
  },
];

const buildPlainText = (idea: string, report: ReportData): string => {
  return `MY SOLOBLUEPRINT\n${idea}\nGenerated by SoloBlueprint · soloblueprint.co.uk\n==========================================\n\n01 · BUSINESS IDEA DIAGNOSIS\n${report.diagnosis}\n\n02 · REAL PROBLEM & DEMAND\n${report.problem_and_demand}\n\n03 · TARGET AUDIENCE\n${report.target_audience}\n\n04 · YOUR CLEAR OFFER\n${report.clear_offer}\n\n05 · TOOLS YOU NEED\n${report.tools_needed}\n\n06 · AI & NO-CODE STACK\n${report.ai_nocode_stack}\n\n07 · STEP-BY-STEP LAUNCH PLAN\n${flattenLaunchPlan(report.launch_plan)}\n\n08 · PRICING STRATEGY\n${report.pricing_strategy}\n\n09 · DISTRIBUTION CHANNELS\n${report.distribution_channels}\n\n10 · OUTREACH SCRIPTS\n${report.outreach_scripts}\n\n11 · PROOF & DEMO TO CREATE\n${report.proof_needed}\n\n12 · HONEST RISKS\n${report.honest_risks}\n\n13 · YOUR FIRST 7-DAY ACTION PLAN\n${report.seven_day_plan}\n\n14 · HOW TO SCALE LATER\n${report.how_to_scale}\n\n==========================================\nBuild your solo business at soloblueprint.co.uk`;
};

const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    const ta = document.createElement("textarea");
    ta.value = text;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand("copy");
    document.body.removeChild(ta);
  }
};

const CopyButton = ({ text, label = "Copy" }: { text: string; label?: string }) => {
  const [done, setDone] = useState(false);
  return (
    <button
      type="button"
      onClick={async (e) => {
        e.stopPropagation();
        await copyToClipboard(text);
        setDone(true);
        setTimeout(() => setDone(false), 1500);
      }}
      className="inline-flex items-center gap-1 rounded-md border border-border bg-background/40 px-2 py-1 text-[10px] font-medium uppercase tracking-wider text-muted-foreground transition hover:border-primary/50 hover:text-foreground"
    >
      {done ? "Copied ✓" : label}
    </button>
  );
};

const PhaseCard = ({ phase, index, defaultOpen }: { phase: LaunchPhase; index: number; defaultOpen: boolean }) => {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="overflow-hidden rounded-lg border border-border bg-background/40">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-start justify-between gap-3 px-4 py-3 text-left transition hover:bg-background/60"
      >
        <div className="flex flex-1 items-baseline gap-3">
          <span className="font-mono-num text-[11px] text-primary">P{index + 1}</span>
          <div className="flex-1">
            <p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">{phase.timeframe}</p>
            <p className="mt-0.5 text-sm font-semibold text-foreground sm:text-[15px]">{phase.title}</p>
          </div>
        </div>
        <span className="mt-1 text-xs text-muted-foreground" aria-hidden>{open ? "−" : "+"}</span>
      </button>
      {open && (
        <div className="space-y-5 border-t border-border px-4 py-4 text-sm leading-relaxed text-muted-foreground sm:text-[14px] sm:leading-[1.7]">
          <div>
            <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-foreground/80">What to do</p>
            <p className="whitespace-pre-line">{phase.what_to_do}</p>
          </div>
          <div>
            <p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-foreground/80">Exact steps</p>
            <ol className="space-y-2">
              {phase.exact_steps.map((step, i) => (
                <li key={i} className="flex gap-3">
                  <span className="font-mono-num shrink-0 text-xs text-primary">{i + 1}.</span>
                  <div className="flex-1">
                    <p className="whitespace-pre-line">{step}</p>
                    <div className="mt-1"><CopyButton text={step} label="Copy step" /></div>
                  </div>
                </li>
              ))}
            </ol>
          </div>
          <div className="rounded-md border border-primary/30 bg-primary/5 p-3">
            <div className="mb-1 flex items-center justify-between gap-2">
              <p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-primary">Real-life example</p>
              <CopyButton text={phase.real_life_example} label="Copy example" />
            </div>
            <p className="whitespace-pre-line text-foreground/90">{phase.real_life_example}</p>
          </div>
          <div>
            <p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-foreground/80">Tools</p>
            <ul className="space-y-1.5">
              {phase.tools.map((tool, i) => (
                <li key={i} className="flex gap-2">
                  <span className="text-primary">•</span>
                  <span className="flex-1 whitespace-pre-line">{tool}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="border-t border-border pt-3">
            <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-foreground/80">What success looks like</p>
            <p className="whitespace-pre-line">{phase.success_looks_like}</p>
          </div>
        </div>
      )}
    </div>
  );
};

const LaunchPlanSection = ({ num, title, plan }: { num: string; title: string; plan: LaunchPlan }) => {
  const isDesktop = typeof window !== "undefined" && window.matchMedia("(min-width: 768px)").matches;
  if (typeof plan === "string" || !plan?.phases?.length) {
    return (
      <article className="animate-fade-in rounded-xl border border-border border-l-2 border-l-primary bg-card p-5 sm:p-6">
        <div className="mb-3 flex items-baseline gap-3">
          <span className="font-mono-num text-xs text-muted-foreground">{num}</span>
          <h2 className="text-base font-semibold text-foreground sm:text-lg">{title}</h2>
        </div>
        <p className="whitespace-pre-line text-sm leading-relaxed text-muted-foreground sm:text-[15px] sm:leading-[1.7]">
          {typeof plan === "string" ? plan : ""}
        </p>
      </article>
    );
  }
  return (
    <article className="animate-fade-in rounded-xl border border-border border-l-2 border-l-primary bg-card p-5 sm:p-6">
      <div className="mb-4 flex items-baseline gap-3">
        <span className="font-mono-num text-xs text-muted-foreground">{num}</span>
        <h2 className="text-base font-semibold text-foreground sm:text-lg">{title}</h2>
      </div>
      <p className="mb-4 text-xs text-muted-foreground sm:text-sm">Five sequential phases covering the first 14 days.</p>
      <div className="space-y-3">
        {plan.phases.map((phase, i) => (
          <PhaseCard key={i} phase={phase} index={i} defaultOpen={isDesktop} />
        ))}
      </div>
    </article>
  );
};

// ── PAYWALL OVERLAY ──
const PaywallGate = ({ ideaName }: { ideaName: string }) => {
  const [selected, setSelected] = useState("monthly");
  const navigate = useNavigate();

  return (
    <div className="relative mt-2">
      {/* Blurred locked sections preview */}
      <div className="pointer-events-none select-none space-y-4 opacity-40 blur-sm">
        {SECTIONS.slice(FREE_SECTIONS).slice(0, 3).map((s) => (
          <div key={s.num} className="rounded-xl border border-border bg-card p-5">
            <div className="mb-2 flex items-baseline gap-3">
              <span className="text-xs text-muted-foreground">{s.num}</span>
              <span className="text-base font-semibold">{s.title}</span>
            </div>
            <div className="h-3 w-3/4 rounded bg-muted/40 mb-2" />
            <div className="h-3 w-1/2 rounded bg-muted/40" />
          </div>
        ))}
      </div>

      {/* Paywall card */}
      <div className="sticky bottom-0 mt-[-80px] rounded-2xl border border-border bg-background/95 shadow-2xl backdrop-blur p-6 sm:p-8">
        <div className="mb-1 text-2xl text-center">🔓</div>
        <h2 className="font-display text-xl text-center mb-1">Unlock your full blueprint</h2>
        <p className="text-sm text-muted-foreground text-center mb-6">
          11 more sections — tools stack, pricing, outreach scripts, 7-day action plan and more.
        </p>

        <div className="space-y-3 mb-5">
          {PLANS.map((plan) => (
            <button
              key={plan.id}
              type="button"
              onClick={() => setSelected(plan.id)}
              className={`w-full flex items-center justify-between rounded-xl border px-4 py-3 text-left transition ${
                selected === plan.id
                  ? "border-primary bg-primary/5"
                  : "border-border hover:border-primary/40"
              }`}
            >
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold">{plan.name}</span>
                  {plan.popular && (
                    <span className="rounded-full bg-primary px-2 py-0.5 text-[10px] font-semibold text-white">
                      Popular
                    </span>
                  )}
                </div>
                <p className="text-xs text-muted-foreground mt-0.5">{plan.desc}</p>
              </div>
              <div className="text-right">
                <span className="font-display text-lg">{plan.price}</span>
                <p className="text-[10px] text-muted-foreground">{plan.period}</p>
              </div>
            </button>
          ))}
        </div>

        <button
          type="button"
          onClick={() => navigate("/auth")}
          className="w-full rounded-xl bg-primary py-3 text-sm font-semibold text-white shadow-[0_4px_20px_rgba(79,70,229,0.35)] transition hover:brightness-110"
        >
          Continue to payment →
        </button>
        <p className="mt-3 text-center text-[11px] text-muted-foreground">
          Secure payment via Stripe · Cancel anytime
        </p>
      </div>
    </div>
  );
};

export const ResultsView = ({ ideaName, answers, report, onStartOver, isPaid = false }: ResultsViewProps) => {
  const [copied, setCopied] = useState(false);
  const [promptCopied, setPromptCopied] = useState(false);

  const copyText = async (text: string) => {
    try { await navigator.clipboard.writeText(text); }
    catch {
      const ta = document.createElement("textarea");
      ta.value = text; document.body.appendChild(ta); ta.select();
      document.execCommand("copy"); document.body.removeChild(ta);
    }
  };

  const handleCopy = async () => { await copyText(buildPlainText(ideaName, report)); setCopied(true); setTimeout(() => setCopied(false), 2000); };
  const handleCopyPrompt = async () => { await copyText(buildMarketingPrompt(ideaName, answers, report)); setPromptCopied(true); setTimeout(() => setPromptCopied(false), 2000); };
  const handleDownloadPdf = () => { downloadBlueprintPdf(ideaName, answers, report); };

  const meta = [answers.budget, answers.hours, answers.experience, answers.goal].filter(Boolean).join(" · ");
  const freeSections = SECTIONS.slice(0, FREE_SECTIONS);
  const lockedSections = SECTIONS.slice(FREE_SECTIONS);

  return (
    <div className="min-h-screen">
      {/* Sticky action bar */}
      <div className="sticky top-0 z-20 border-b border-border bg-background/85 backdrop-blur supports-[backdrop-filter]:bg-background/70">
        <div className="mx-auto flex max-w-[820px] items-center justify-between gap-3 px-4 py-3 sm:px-6">
          <Logo size="sm" />
          <div className="flex flex-wrap items-center justify-end gap-2">
            {isPaid && (
              <>
                <button onClick={handleDownloadPdf} className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground shadow-[0_8px_24px_-12px_hsl(var(--primary)/0.7)] transition hover:brightness-110 sm:text-sm">↓ PDF</button>
                <button onClick={handleCopyPrompt} className="rounded-lg border border-primary/60 bg-transparent px-3 py-2 text-xs font-semibold text-primary transition hover:bg-primary/10 sm:text-sm">{promptCopied ? "Copied ✓" : "Marketing Prompt"}</button>
                <button onClick={handleCopy} className="rounded-lg border border-border bg-transparent px-3 py-2 text-xs font-medium text-muted-foreground transition hover:border-primary/50 hover:text-foreground sm:text-sm">{copied ? "Copied ✓" : "Copy Plan"}</button>
              </>
            )}
            <button onClick={onStartOver} className="rounded-lg px-3 py-2 text-xs font-medium text-muted-foreground transition hover:text-foreground sm:text-sm">Start Over</button>
          </div>
        </div>
      </div>

      <main className="mx-auto w-full max-w-[820px] px-4 py-10 sm:px-6 sm:py-14">
        <p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Your SoloBlueprint for:</p>
        <h1 className="mt-2 font-display text-3xl text-foreground sm:text-4xl md:text-5xl">{ideaName}</h1>
        {meta && <p className="mt-3 text-xs text-muted-foreground sm:text-sm">{meta}</p>}

        {/* Free sections */}
        <div className="mt-10 space-y-5">
          {freeSections.map((section) => (
            <article key={section.num} className="animate-fade-in rounded-xl border border-border border-l-2 border-l-primary bg-card p-5 sm:p-6">
              <div className="mb-3 flex items-baseline gap-3">
                <span className="font-mono-num text-xs text-muted-foreground">{section.num}</span>
                <h2 className="text-base font-semibold text-foreground sm:text-lg">{section.title}</h2>
              </div>
              <p className="whitespace-pre-line text-sm leading-relaxed text-muted-foreground sm:text-[15px] sm:leading-[1.7]">
                {report[section.key] as string}
              </p>
            </article>
          ))}
        </div>

        {/* Paid sections or paywall */}
        {isPaid ? (
          <div className="mt-5 space-y-5">
            {lockedSections.map((section) => {
              if (section.key === "launch_plan") {
                return <LaunchPlanSection key={section.num} num={section.num} title={section.title} plan={report.launch_plan} />;
              }
              return (
                <article key={section.num} className="animate-fade-in rounded-xl border border-border border-l-2 border-l-primary bg-card p-5 sm:p-6">
                  <div className="mb-3 flex items-baseline gap-3">
                    <span className="font-mono-num text-xs text-muted-foreground">{section.num}</span>
                    <h2 className="text-base font-semibold text-foreground sm:text-lg">{section.title}</h2>
                  </div>
                  <p className="whitespace-pre-line text-sm leading-relaxed text-muted-foreground sm:text-[15px] sm:leading-[1.7]">
                    {report[section.key] as string}
                  </p>
                </article>
              );
            })}
          </div>
        ) : (
          <PaywallGate ideaName={ideaName} />
        )}

        <footer className="mt-14 border-t border-border pt-6 text-center text-xs text-muted-foreground">
          SoloBlueprint · Built for solo founders · soloblueprint.co.uk
        </footer>
      </main>
    </div>
  );
};
